[package]
name = "takumi-pdf-wasm"
publish = false
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys.workspace = true
serde-wasm-bindgen.workspace = true
serde_bytes.workspace = true
wasm-bindgen.workspace = true

[dependencies.serde]
workspace = true
features = ["rc"]

[dependencies.takumi-bindings-common]
path = "../takumi-bindings-common"

[dependencies.takumi-core]
path = "../takumi-core"
default-features = false
features = ["woff2"]

[dependencies.takumi-pdf]
path = "../takumi-pdf"

[lints]
workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
  '-Oz',
  '--converge',
  '--code-folding',
  '--enable-bulk-memory',
  '--enable-simd',
  '--enable-nontrapping-float-to-int',
  '--enable-mutable-globals',
  '--enable-sign-ext',
  '--strip-debug',
  '--strip-dwarf',
  '--strip-producers',
  '--strip-target-features',
]
