name: Setup Rust
description: Setup Rust toolchain, cache, and install cargo-binstall

inputs:
  binstall:
    description: Install cargo-binstall
    required: false
  toolchain:
    description: Rust toolchain to install
    required: false
    default: stable
  targets:
    description: Targets to install
    required: false
  components:
    description: Components to install
    required: false
  stage:
    description: Stage of the action
    required: true
    type: choice
    options:
      - test
      - build
      - publish

runs:
  using: composite
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master 2026-07
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Rust Cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        prefix-key: rust-${{ inputs.stage }}

    - name: Install cargo-binstall
      if: ${{ inputs.binstall }}
      uses: taiki-e/install-action@67729d5c413db75907f0ad1e39bb04b9c868ff60 # v2.85.7
      with:
        tool: ${{ inputs.binstall }}
