[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies.imagen]
path = "../imagen"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies]
typetag = "0.2"
async-trait = "0.1"