[package]
name = "image-gen-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
tokio = { version = "1", features = ["full"] }
image = "0.25"
imageproc = "0.25"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.0"
ttf-parser = "0.25"
ab_glyph = "0.2"
woff2-patched = "0.4"
mimalloc = "0.1"
serde_json = "1.0"
lru = "0.14.0"

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["rustls-tls", "http2"]
