[package]
name = "takumi-css"
version = "0.2.0-rc.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "CSS parsing and style resolution layer for takumi."
repository = "https://github.com/kane50613/takumi"
readme = "README.md"
rust-version = "1.91"

[dependencies]
bitflags.workspace = true
cssparser.workspace = true
paste.workspace = true
color.workspace = true
thiserror.workspace = true
typed-builder.workspace = true
precomputed-hash.workspace = true
tiny-skia.workspace = true
kurbo.workspace = true
bytemuck.workspace = true
selectors.workspace = true
smallvec.workspace = true
phf.workspace = true
parley.workspace = true
taffy.workspace = true
image.workspace = true

[dependencies.serde]
workspace = true
features = ["rc"]

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true


