[package]
name = "takumi-c-ffi"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT OR Apache-2.0"
build = "build.rs"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies.takumi]
path = "../takumi"
features = ["woff2", "woff", "svg", "detailed_css_error"]
default-features = false

[build-dependencies]
cbindgen = "0.29"
