import { writeFile } from "node:fs/promises";
import { defineConfig } from "tsdown";
import { fetchOk } from "./src/utils.ts";

const CATALOG_SOURCE = "https://fonts.google.com/metadata/fonts";
const CATALOG_FILE = new URL("src/google-fonts-catalog.ts", import.meta.url);

interface FamilyMetadata {
  family: string;
  fonts: Record<string, unknown>;
  axes?: { tag: string }[];
}

async function generateCatalog() {
  const data: { familyMetadataList: FamilyMetadata[] } = await fetchOk(CATALOG_SOURCE)
    .then((r) => r.json())
    .catch((error) => {
      throw error.name === "TimeoutError"
        ? new Error(`${CATALOG_SOURCE} timed out after 30s`)
        : error;
    });

  const families = [...data.familyMetadataList].sort((a, b) => (a.family < b.family ? -1 : 1));

  // Guard against an empty or truncated response silently emitting a broken catalog.
  if (families.length < 1000) {
    throw new Error(
      `${CATALOG_SOURCE} returned ${families.length} families (<1000); refusing to write a truncated catalog`,
    );
  }

  // Group families by shape so the consumer union is one branch per distinct shape, not per family.
  const shapeNames = new Map<string, string>();
  const shapeFamilies = new Map<string, string[]>();

  for (const { family, fonts, axes } of families) {
    const weights = new Set<number>();
    const styles = new Set<string>();
    for (const variant of Object.keys(fonts)) {
      const italic = variant.endsWith("i");
      const value = italic ? variant.slice(0, -1) : variant;
      if (!/^\d+$/.test(value)) {
        continue;
      }
      styles.add(italic ? "italic" : "normal");
      weights.add(Number(value));
    }

    const weight = [...weights].sort((a, b) => a - b).join(" | ");
    const style = [...styles]
      .sort()
      .map((s) => `"${s}"`)
      .join(" | ");
    // ital and wght are driven by style/weight, and buildUrl drops them from custom axes.
    const extraAxes = (axes ?? [])
      .map((a) => a.tag)
      .filter((tag) => tag !== "wght" && tag !== "ital")
      .sort();
    const axis = extraAxes.length ? extraAxes.map((tag) => `"${tag}"`).join(" | ") : "never";

    const shape = `{ weight: ${weight}; style: ${style}; axis: ${axis} }`;
    let name = shapeNames.get(shape);
    if (name === undefined) {
      name = `S${shapeNames.size}`;
      shapeNames.set(shape, name);
    }

    const namesForShape = shapeFamilies.get(name);
    if (namesForShape) {
      namesForShape.push(family);
    } else {
      shapeFamilies.set(name, [family]);
    }
  }

  const shapeLines = [...shapeNames.entries()].map(([shape, name]) => `  ${name}: ${shape};`);
  const shapeFamilyLines = [...shapeFamilies.entries()].map(
    ([name, names]) => `  ${name}: ${names.map((f) => JSON.stringify(f)).join(" | ")};`,
  );

  await writeFile(
    CATALOG_FILE,
    `// Generated by tsdown.config.ts from ${CATALOG_SOURCE} (${families.length} families).
// Do not edit, do not commit.

export interface GoogleFontShapes {
${shapeLines.join("\n")}
}

// Families sharing each shape in GoogleFontShapes; its values form the flat name union.
export interface GoogleFontShapeFamilies {
${shapeFamilyLines.join("\n")}
}
`,
  );
}

// Regenerate before every build so the published types track the latest families.
await generateCatalog();

export default defineConfig({
  entry: {
    index: "src/index.ts",
    emoji: "src/emoji.ts",
    jsx: "src/jsx/index.ts",
    html: "src/html/index.ts",
    renderer: "src/renderer.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  publint: {
    enabled: "ci-only",
    level: "error",
  },
  deps: {
    onlyBundle: ["ultrahtml"],
  },
  minify: true,
  clean: true,
  outDir: "dist",
});
