import { access, writeFile } from "node:fs/promises";
import { defineConfig } from "tsdown";

const CATALOG_SOURCE = "https://fonts.google.com/metadata/fonts";
const CATALOG_FILE = new URL("src/google-fonts-catalog.ts", import.meta.url);

interface FamilyMetadata {
  family: string;
  fonts: Record<string, unknown>;
  axes?: { tag: string }[];
}

/** Build the gitignored `src/google-fonts-catalog.ts` from the public Google Fonts metadata (no API key). */
async function generateCatalog() {
  const data: { familyMetadataList: FamilyMetadata[] } = await fetch(CATALOG_SOURCE).then((r) => {
    if (!r.ok) {
      throw new Error(`${CATALOG_SOURCE} → ${r.status}`);
    }
    return r.json();
  });

  const families = [...data.familyMetadataList].sort((a, b) => (a.family < b.family ? -1 : 1));

  const lines = families.map(({ family, fonts, axes }) => {
    const weights = new Set<number>();
    const styles = new Set<string>();
    for (const variant of Object.keys(fonts)) {
      const italic = variant.endsWith("i");
      styles.add(italic ? "italic" : "normal");
      weights.add(Number(italic ? variant.slice(0, -1) : variant));
    }

    const weight = [...weights].sort((a, b) => a - b).join(" | ");
    const style = [...styles]
      .sort()
      .map((s) => `"${s}"`)
      .join(" | ");
    const extraAxes = (axes ?? [])
      .map((a) => a.tag)
      .filter((tag) => tag !== "wght")
      .sort();
    const axis = extraAxes.length ? extraAxes.map((tag) => `"${tag}"`).join(" | ") : "never";

    return `  ${JSON.stringify(family)}: { weight: ${weight}; style: ${style}; axis: ${axis} };`;
  });

  await writeFile(
    CATALOG_FILE,
    `// Generated by tsdown.config.ts — do not edit, do not commit.
// Source: ${CATALOG_SOURCE} (${families.length} families)

/** Per-family weight, style, and variable-axis metadata from Google Fonts. */
export interface GoogleFontCatalog {
${lines.join("\n")}
}
`,
  );
}

// Generate the catalog before the build resolves it. Reuse the local copy in dev; refresh in CI
// (and on demand with REFRESH_GOOGLE_FONTS) so the published types track the latest families.
const hasCatalog = await access(CATALOG_FILE).then(
  () => true,
  () => false,
);
if (!hasCatalog || process.env.CI || process.env.REFRESH_GOOGLE_FONTS) {
  await generateCatalog();
}

export default defineConfig({
  entry: {
    index: "src/index.ts",
    emoji: "src/emoji.ts",
    jsx: "src/jsx/index.ts",
    html: "src/html/index.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  publint: {
    enabled: "ci-only",
    level: "error",
  },
  deps: {
    onlyBundle: ["ultrahtml"],
  },
  minify: true,
  clean: true,
  outDir: "dist",
});
