[package]
name = "takumi-server"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
axum.workspace = true
globwalk.workspace = true
mimalloc.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde_json.workspace = true
query-string-builder.workspace = true
serde.workspace = true
tokio.workspace = true
clap.workspace = true

[dev-dependencies]
tower.workspace = true

[dependencies.hex]
workspace = true
optional = true

[dependencies.hmac]
workspace = true
optional = true

[dependencies.sha2]
workspace = true
optional = true

[dependencies.takumi]
path = "../takumi"

[features]
default = ["hmac_verify"]
hmac_verify = ["dep:hmac", "dep:sha2", "dep:hex"]

[lints]
workspace = true
