[package]
name = "takumi"
version = "0.6.0"
edition = "2024"
license = "MIT"
description = "High-performance Rust library for generating images with CSS Flexbox-like layouts."
keywords = ["image", "css", "flexbox", "layout", "rendering"]
repository = "https://github.com/kane50613/takumi"
readme = "README.md"
exclude = ["benches/**/*"]
rust-version = "1.85.1"

[dependencies]
imageproc = "0.25"
woff2-patched = "0.4"
futures-util = "0.3"
bytes = "1.10"
async-trait = "0.1"
merge = "0.2"
ts-rs = "11.0"
slotmap = "1.0.7"
rayon = "1.10.0"

[dependencies.reqwest]
version = "0.12"
default-features = false
features = ["rustls-tls", "http2"]
optional = true

[dependencies.lru]
version = "0.14"
optional = true

[dependencies.cosmic-text]
version = "0.14"
features = ["shape-run-cache", "hashbrown"]

[dependencies.taffy]
version = "0.8"
features = ["serde"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.image]
default-features = false
version = "0.25"
features = ["jpeg", "png", "webp"]

[dev-dependencies.criterion]
version = "0.6"
features = ["html_reports"]
default-features = false

[[bench]]
name = "takumi"
harness = false

[features]
default = ["default_impl"]
default_impl = ["image_store_impl", "node_kind_enum_impl"]
image_store_impl = ["dep:reqwest", "dep:lru"]
node_kind_enum_impl = []
