[package]
name = "takumi"
version = "1.8.5"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Render UI component trees to images."
keywords = ["react", "image", "css", "flexbox"]
repository = "https://github.com/kane50613/takumi"
homepage = "https://takumi.kane.tw"
readme = "README.md"
rust-version = "1.91"
autobenches = false

[dependencies.takumi-core]
path = "../takumi-core"
version = "=1"
default-features = false

[dependencies.takumi-paint]
path = "../takumi-paint"
version = "=1"
default-features = false
optional = true

[dependencies.takumi-svg]
path = "../takumi-svg"
version = "=0.1"
default-features = false
optional = true

[features]
default = ["paint", "woff2", "woff", "svg", "rayon"]
paint = ["dep:takumi-paint"]
svg = ["takumi-core/svg", "takumi-paint?/svg"]
svg-backend = ["dep:takumi-svg"]
woff2 = ["takumi-core/woff2"]
woff = ["takumi-core/woff"]
rayon = ["paint", "takumi-paint?/rayon"]

[dev-dependencies]
parley.workspace = true
rayon.workspace = true
resvg = "0.47"
serde_json.workspace = true

[dev-dependencies.image]
workspace = true
features = ["png", "webp"]

[dev-dependencies.takumi-svg]
path = "../takumi-svg"

[lints]
workspace = true
