name: Publish to npm

inputs:
  working_directory:
    description: Directory containing package.json
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4

    - name: Publish
      working-directory: ${{ inputs.working_directory }}
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        npm publish --access public --provenance
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
