[package]
name = "takumi-napi-core"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
rayon.workspace = true
parley.workspace = true
napi.workspace = true
napi-derive.workspace = true

[dependencies.takumi-base]
path = "../takumi-base"
default-features = false
features = ["woff2", "woff", "svg"]

[dependencies.takumi-raster]
path = "../takumi-raster"
default-features = false
features = ["svg", "rayon"]

[build-dependencies]
napi-build.workspace = true

[lints]
workspace = true
