// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Represents a single transform function (internal canonical form).
 */
export type TransformFunction = { "translate": [LengthUnit, LengthUnit] } | { "scale": [number, number] } | { "rotate": number } | { "skew": [number, number] };
