// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LengthUnit } from "./LengthUnit";

/**
 * Transform origin (x,y) relative or absolute lengths.
 */
export type TransformOrigin = [LengthUnit, LengthUnit];
