// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransformFunction } from "./TransformFunction";

/**
 * Collection of transform functions in order.
 */
export type Transform = Array<TransformFunction>;
