name: Takumi NAPI Core CI

env:
  DEBUG: napi:*
  APP_NAME: core
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CARGO_INCREMENTAL: "1"

permissions:
  contents: write
  id-token: write

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            build: napi build --release --platform --strip --target aarch64-apple-darwin
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build: napi build --release --platform --strip --target aarch64-unknown-linux-gnu
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build: |-
              rustup target add aarch64-unknown-linux-musl &&
              napi build --release --platform --strip --target aarch64-unknown-linux-musl
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            build: napi build --release --platform --strip --target x86_64-unknown-linux-gnu
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build: |-
              rustup target add x86_64-unknown-linux-musl &&
              napi build --release --platform --strip --target x86_64-unknown-linux-musl

    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: takumi-napi-core
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            takumi-napi-core/target/
          key: ${{ matrix.settings.target }}-cargo-${{ matrix.settings.host }}

      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: takumi-napi-core/${{ env.APP_NAME }}.*.node
          if-no-files-found: error

  test-bindings:
    name: Test ${{ matrix.settings.target }} - node@${{ matrix.node }}
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: aarch64-apple-darwin
            architecture: arm64
            test_cmd: bun test
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            architecture: x64
            test_cmd: bun test
          - host: ubuntu-latest
            target: x86_64-unknown-linux-musl
            architecture: x64
            test_cmd: bun test
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            architecture: x64
            test_cmd: bun test
          - host: ubuntu-latest
            target: aarch64-unknown-linux-musl
            architecture: x64
            test_cmd: bun test
        node:
          - "20"
          - "22"
    runs-on: ${{ matrix.settings.host }}
    defaults:
      run:
        working-directory: takumi-napi-core
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.settings.architecture }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: takumi-napi-core

      - name: Test bindings
        run: ${{ matrix.settings.test_cmd }}
        shell: bash
